"""empty message

Revision ID: 39bee462aa64
Revises: 4ec004fa7f4d
Create Date: 2020-04-15 13:36:03.511083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bee462aa64'
down_revision = '4ec004fa7f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_securities',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followed_securities')
    # ### end Alembic commands ###
