"""empty message

Revision ID: c922403aa648
Revises: 34a8b3a88a74
Create Date: 2020-04-27 18:33:26.494884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c922403aa648'
down_revision = '34a8b3a88a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('testfield', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'testfield')
    # ### end Alembic commands ###
