"""add information to security

Revision ID: cea7abf9b842
Revises: e7beb002172f
Create Date: 2020-04-21 21:01:29.483817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea7abf9b842'
down_revision = 'e7beb002172f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('security', sa.Column('sector', sa.String(length=64), nullable=True))
    op.add_column('security', sa.Column('summary', sa.String(length=1024), nullable=True))
    op.add_column('security', sa.Column('website', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_security_name'), 'security', ['name'], unique=False)
    op.create_index(op.f('ix_security_sector'), 'security', ['sector'], unique=False)
    op.create_index(op.f('ix_security_summary'), 'security', ['summary'], unique=False)
    op.create_index(op.f('ix_security_website'), 'security', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_website'), table_name='security')
    op.drop_index(op.f('ix_security_summary'), table_name='security')
    op.drop_index(op.f('ix_security_sector'), table_name='security')
    op.drop_index(op.f('ix_security_name'), table_name='security')
    op.drop_column('security', 'website')
    op.drop_column('security', 'summary')
    op.drop_column('security', 'sector')
    op.drop_column('security', 'name')
    # ### end Alembic commands ###
